ktor:
  application:
    modules:
      - com.facundo.ApplicationKt.module
  deployment:
    port: 8082

database:
  url: "jdbc:postgresql://localhost:5433/taskflow_chat"
  driver: "org.postgresql.Driver"
  user: "taskflow"
  password: "taskflow123"

jwt:
  secret: "secreto-local-cambiar-en-produccion"
  issuer: "taskflow-chat"
  audience: "taskflow-users"
  realm: "taskflow-chat"