ktor:
  application:
    modules:
      - com.facundo.ApplicationKt.module  # coincide con tu group
  deployment:
    port: 8082  # 8081 para no chocar con la Fase 1 en 8080

database:
  url: "jdbc:postgresql://localhost:5433/taskflow_chat"
  driver: "org.postgresql.Driver"
  user: "taskflow"
  password: "taskflow123"

jwt:
  secret: "secreto-local-cambiar-en-produccion"
  issuer: "taskflow-chat"
  audience: "taskflow-users"
  realm: "taskflow-chat"